import type {Metadata} from 'next';
import {Roboto} from 'next/font/google';
import {JSX, ReactNode} from 'react';
import Container from './components/Container';
import {Header} from './components/Header';
import './styles/globals.css';

// eslint-disable-next-line new-cap
const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['latin'],
  style: ['normal', 'italic'],
});

export const metadata: Metadata = {
  title: 'Shop',
  description: 'Generated by create next app',
};

/**
 * Root layout component.
 *
 * @param {Object} props - The component props.
 * @param {ReactNode} props.children - The children elements.
 * @return {JSX.Element} The rendered component.
 */
export default function RootLayout({
  children,
}: Readonly<{
    children: ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased bg-gray-900 text-gray-100`}>
        <Container>
          <Header />
          {children}
        </Container>
      </body>
    </html>
  );
}
